-- CreateTable
CREATE TABLE "Setting" (
    "id" SERIAL NOT NULL,
    "razaoSocial" TEXT,
    "nomeFantasia" TEXT,
    "cnpj" TEXT,
    "telefone" TEXT,
    "whatsapp" TEXT,
    "email" TEXT,
    "endereco" TEXT,
    "numero" TEXT,
    "bairro" TEXT,
    "cidade" TEXT,
    "uf" TEXT,
    "cep" TEXT,
    "horarioFuncionamento" TEXT,
    "taxaServico" DOUBLE PRECISION,
    "couvert" DOUBLE PRECISION,
    "rodapeCupom" TEXT,
    "logoUrl" TEXT,
    "usaMesa" BOOLEAN NOT NULL DEFAULT true,
    "usaComanda" BOOLEAN NOT NULL DEFAULT true,
    "comandaObrigatoria" BOOLEAN NOT NULL DEFAULT false,
    "qtdMesas" INTEGER,
    "separarPedidoPorSetor" BOOLEAN NOT NULL DEFAULT true,
    "bloquearVendaSemEstoque" BOOLEAN NOT NULL DEFAULT true,
    "exigirObservacaoCancelamento" BOOLEAN NOT NULL DEFAULT true,
    "permitirDescontoLivre" BOOLEAN NOT NULL DEFAULT false,
    "impressoraCozinha" TEXT,
    "impressoraBar" TEXT,
    "impressoraCaixa" TEXT,
    "tamanhoPapel" TEXT,
    "imprimirAutomaticamente" BOOLEAN NOT NULL DEFAULT true,
    "imprimirDuasVias" BOOLEAN NOT NULL DEFAULT false,
    "imprimirNomeGarcom" BOOLEAN NOT NULL DEFAULT true,
    "imprimirHorario" BOOLEAN NOT NULL DEFAULT true,
    "somNovoPedido" BOOLEAN NOT NULL DEFAULT true,
    "alertaPedidoPronto" BOOLEAN NOT NULL DEFAULT true,
    "alertaMesaAbertaSemConsumo" BOOLEAN NOT NULL DEFAULT false,
    "tempoAlertaMesaSemConsumo" INTEGER,
    "tema" TEXT,
    "formatoData" TEXT,
    "fusoHorario" TEXT,
    "logoutAutomaticoMinutos" INTEGER,
    "forcarTrocaSenhaPadrao" BOOLEAN NOT NULL DEFAULT true,
    "exibirAtalhosInicio" BOOLEAN NOT NULL DEFAULT true,
    "whatsappToken" TEXT,
    "webhookPedidos" TEXT,
    "ifoodHabilitado" BOOLEAN NOT NULL DEFAULT false,
    "apiEntregaHabilitada" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Setting_pkey" PRIMARY KEY ("id")
);
